"""
👻 PHANTOM - Report Generator

Generate professional security assessment reports.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Any
from jinja2 import Template
from phantom.logger import get_logger
from phantom.config import PhantomConfig

logger = get_logger("phantom.reporting.generator")


class ReportGenerator:
    """Professional security report generation."""
    
    def __init__(self, config: PhantomConfig):
        self.config = config
        self.output_dir = Path(config.reporting.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        logger.info("Report generator initialized")
    
    async def generate(
        self,
        session_id: str,
        report_format: str = "html",
        include_recommendations: bool = True,
    ) -> str:
        """
        Generate security assessment report.
        
        Args:
            session_id: Session ID to generate report for
            report_format: Format (html, pdf, json, md)
            include_recommendations: Include remediation recommendations
            
        Returns:
            Path to generated report
        """
        logger.info(f"Generating {report_format} report for session {session_id}")
        
        # Gather session data (placeholder)
        report_data = {
            "session_id": session_id,
            "company": self.config.reporting.company_name,
            "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "findings": [],
            "summary": "Security assessment completed",
        }
        
        # Generate report based on format
        if report_format == "html":
            report_path = await self._generate_html(report_data)
        elif report_format == "json":
            report_path = await self._generate_json(report_data)
        elif report_format == "md":
            report_path = await self._generate_markdown(report_data)
        else:
            report_path = await self._generate_html(report_data)
        
        logger.info(f"Report generated: {report_path}")
        return str(report_path)
    
    async def _generate_html(self, data: Dict[str, Any]) -> Path:
        """Generate HTML report."""
        template_path = Path(__file__).parent / "templates" / "report.html.jinja2"
        
        if template_path.exists():
            with open(template_path) as f:
                template = Template(f.read())
            html = template.render(**data)
        else:
            # Fallback simple HTML
            html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>PHANTOM Security Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #8B5CF6; }}
        .header {{ background: linear-gradient(135deg, #8B5CF6, #6366F1); color: white; padding: 20px; border-radius: 8px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>👻 PHANTOM Security Assessment Report</h1>
        <p>Session: {data['session_id']}</p>
        <p>Date: {data['date']}</p>
    </div>
    <h2>Summary</h2>
    <p>{data['summary']}</p>
</body>
</html>
"""
        
        report_path = self.output_dir / f"report_{data['session_id']}.html"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(html)
        
        return report_path
    
    async def _generate_json(self, data: Dict[str, Any]) -> Path:
        """Generate JSON report."""
        report_path = self.output_dir / f"report_{data['session_id']}.json"
        with open(report_path, "w") as f:
            json.dump(data, f, indent=2)
        return report_path
    
    async def _generate_markdown(self, data: Dict[str, Any]) -> Path:
        """Generate Markdown report."""
        md = f"""# 👻 PHANTOM Security Assessment Report

**Session:** {data['session_id']}
**Date:** {data['date']}
**Company:** {data['company']}

## Summary

{data['summary']}

## Findings

Total findings: {len(data['findings'])}

---
Generated by PHANTOM MCP
"""
        
        report_path = self.output_dir / f"report_{data['session_id']}.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(md)
        
        return report_path
